In [1]:
#import the required libraries
import numpy as np
from numpy import genfromtxt

In [2]:
#give path of the source-file and store that path in a variable named census
census = '/content/makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [3]:
data = np.genfromtxt(census, delimiter = ',', skip_header = 1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [4]:
data.dtype

dtype('float64')

# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [5]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [6]:
np.concatenate((data,new_record),axis=0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [ ]:
#display after appending the new record at the end of the array.

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [7]:
age=data[:,0]
age

array([39., 50., 38., 53., 28., 37., 49., 52., 31., 42., 37., 30., 23.,
       32., 40., 34., 25., 32., 38., 43., 40., 54., 35., 43., 59., 56.,
       19., 54., 39., 49., 23., 20., 45., 30., 22., 48., 21., 19., 31.,
       48., 31., 53., 24., 49., 25., 57., 53., 44., 41., 29., 25., 18.,
       47., 50., 47., 43., 46., 35., 41., 30., 30., 32., 48., 42., 29.,
       36., 28., 53., 49., 25., 19., 31., 29., 23., 79., 27., 40., 67.,
       18., 31., 18., 52., 46., 59., 44., 53., 49., 33., 30., 43., 57.,
       37., 28., 30., 34., 29., 48., 37., 48., 32., 76., 44., 47., 20.,
       29., 32., 17., 30., 31., 42., 24., 38., 56., 28., 36., 53., 56.,
       49., 55., 22., 21., 40., 30., 29., 19., 47., 20., 31., 35., 39.,
       28., 24., 38., 37., 46., 38., 43., 27., 20., 49., 61., 27., 19.,
       45., 70., 31., 22., 36., 64., 43., 47., 34., 33., 21., 52., 48.,
       23., 71., 29., 42., 68., 25., 44., 28., 45., 36., 39., 46., 18.,
       66., 27., 28., 51., 27., 28., 27., 21., 34., 18., 33., 44

Find the max age and store it in a variable called 'max_age'.



In [ ]:
#print the max_age
max_age=age.max()
max_age

90.0

Find the min age and store it in a variable called 'min_age'.

In [ ]:
#print the min_age
min_age=age.min()
min_age

17.0

Find the mean of the age and store it in a variable called 'age_mean'.

In [ ]:
#print the age_mean
age_mean=age.mean()
age_mean

38.051

Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
#print the age_std
age_std=age.std()
age_std

13.342803266180612

# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [ ]:
race_0 = data[data[:, 2] == 0]
race_1 = data[data[:, 2] == 1]
race_2 = data[data[:, 2] == 2]
race_3 = data[data[:, 2] == 3]
race_4 = data[data[:, 2] == 4]

print(f"Race 0: {race_0}\n")
# print(f"Race 1:{race_1}\n")
# print(f"Race 2:{race_2}\n")
# print(f"Race 3:{race_3}\n")
# print(f"Race 4:{race_4}\n")


Race 0: [[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]



Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
len_0=len(race_0)
len_0

10

In [ ]:
len_1=len(race_1)
len_1

27

In [ ]:
len_2=len(race_2)
len_2

110

In [ ]:
len_3=len(race_3)
len_3

6

In [ ]:
len_4=len(race_4)
len_4

847

Find out which is the race with the minimum no. of citizens

In [ ]:
min_citizen=np.argmin([ 'len_0', 'len_1','len_2', 'len_3' ,'len_4' ])
print(f"The race with minimum citizens is Race : {min_citizen}")

The race with minimum citizens is Race : 0


Find out which is the race with the minimum no. of citizens

In [ ]:
max_citizen=np.argmax([ 'len_0', 'len_1','len_2', 'len_3' ,'len_4' ])
print(f"The race with maximum citizens is Race : {max_citizen}")

The race with maximum citizens is Race : 4


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race=np.argmin([ 'len_0', 'len_1','len_2', 'len_3' ,'len_4' ])
minority_race

0

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
majority_race = np.argmax([ 'len_0', 'len_1','len_2', 'len_3' ,'len_4' ])
majority_race

4

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [ ]:
#from age column, filter out age data > 60
senior_citizens = data[np.where(data[:, 0] > 60)]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [ ]:
working_hours_sum=senior_citizens[:,6].sum()
working_hours_sum

1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [ ]:
senior_citizens_len=len(senior_citizens)
senior_citizens_len

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [ ]:
avg_working_hours= working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
print(f" No the policy is not being followed because the average rate is :{avg_working_hours} , exceding the critera.")

 No the policy is not being followed because the average rate is :31.42622950819672 , exceding the critera.


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [ ]:
high = data[data[:, 1] > 10]
low = data[data[:, 1] <= 10]
print(high,low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]] [[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [35.  9.  4. ...  0. 45.  0.]
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]]


Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
avg_pay_high = high[:, 7].mean()
avg_pay_low = low[:, 7].mean()
print(avg_pay_high,avg_pay_low)


0.42813455657492355 0.13670133729569092


average pay for low educated people 0.14
